### ISSUE TITLE
Adding Commitlint

### ISSUE THREAD

**Issue by ardguezsoc** [onebeyond/react-form-builder#90]
**Is your feature request related to a problem? Please describe.**

- There is no consistency in the commits to the repository

**Describe the solution you'd like**

- Adding commitlint as a dependency and include a commit check in a pre-commit hook to avoid commiting without following best practices.

**Useful links:**

https://www.conventionalcommits.org/en/v1.0.0/
https://github.com/conventional-changelog/commitlint

**Comment by sofisdev** [comment]
I pushed this [PR](https://github.com/guidesmiths/react-form-builder/pull/91#issue-1016728316) to solve this issue 🤓

**Comment by ardguezsoc** [comment]
Nice job thx for fixing it 😄
